git:
  depth: 5

stages:
  - "Build and Test"
  - "Package"

jobs:
  include:
    - stage: "Build and Test"
      language: java
      jdk: oraclejdk11
      before_script:
       - cd sample-application-backend
      script:
       - echo "Maven build"
       - echo "Run test coverage and Quality Gate"
       - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=GregoireChateau9_sample-application-students
    - stage: "Build and Test"
      language: node.js
      node_js: "12.20"
      before_script:
        - cd sample-application-frontend
      script:
        - echo "NPM install and build"
    - stage: "Package"
      before_script:
        - cd sample-application-backend
      script:
        - docker build -t chateauneuf/back_sample_application_student .
        - docker login -u $DOCKERUSR -p $DOCKERPSW
        - docker push chateauneuf/back_sample_application_student
    - stage: "Package"
      before_script:
        - cd sample-application-frontend
      script:
        - docker build -t chateauneuf/front_sample_application_student .
        - docker login -u $DOCKERUSR -p $DOCKERPSW
        - docker push chateauneuf/front_sample_application_student

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"

services:
  - docker

addons:
  sonarcloud:
    organization: "chateauneuf"
    token: "$SONARCLOUD_TOKEN"